server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/wablog?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
#       使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # druid配置项，默认spring-boot不支持，故需要config类来解析
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    jpa:
        database: mysql
        show-sql: true
        open-in-view: true
        hibernate:
          ddl-auto: update

    thymeleaf:
        prefix: classpath:/templates/
        mode: HTML
        cache: false

    servlet:
      multipart:
        enabled: true
        max-file-size: 50mb
        max-request-size: 50mb
    # security
#    security:
#      user:
#        name: waver
#        password: waver
    mvc:
      favicon:
        enabled: false

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
